### ISSUE TITLE
Does not work when using the specified index

### ISSUE THREAD

**Issue by captain-neo** [tortoise/aerich#203]
version: 0.5.8

while using the `tortoise.indexes.Index` based index class，migration doesn't work at all
ex:
```python
from tortoise.contrib.postgres.indexes import GinIndex

class Model(...):
    class Meta:
        indexes = [GinIndex(fields={"scopes"})]
```
when `aerich init-db`
```
TypeError: Object of type GinIndex is not JSON serializable
```

**Comment by panicneo** [comment]
additional, 
tortoise-orm generate schema feature does works

**Comment by fullonic** [comment]
Hey @captain-neo ! I'm having the same issue. Have you found a solution? Thanks

**Comment by fullonic** [comment]
@long2ice To put some more context, the issue happens when aerich saves the app information to aerich table JSONField. Is because that it works when the schema is generated by Tortoise but not when using aerich.
If we commented out the `aerich.__init__` ** line 130** it solves the issue related to JSON serialization and the SQL migration file is generated. However, the generated SQL file by aerich doesn't have the information about the index type, it generates a _regular_ index.

**Comment by fullonic** [comment]
Thanks, @long2ice for https://github.com/tortoise/aerich/commit/f15cbaf9e0269fca88741fae135bc7952fafd444
When can we have a release with these changes? 
Thanks again :+1:

**Comment by long2ice** [comment]
Just try it

**Comment by captain-neo** [comment]
我都忘了提过这个issue了，哈哈，辛苦。

**Comment by fullonic** [comment]
@long2ice it works well. I tested the upgrade and downgrade and both went well. Nice work. Thanks!

**Comment by long2ice** [comment]
OK, I will release it in proper time
