### ISSUE TITLE
tortoise.exceptions.ConfigurationError: Module "/migrations.models.old_models" not found

### ISSUE THREAD

**Issue by MAOA-L** [tortoise/aerich#89]
when exec aerich migrate or aerich upgrade.
There is a issue with Module "/migrations.models.old_models" not found

**Comment by TrDex** [comment]
Hello! Are you running this on Windows?

**Comment by TrDex** [comment]
I just checked out the sources. For now, you can simply change line 186 (as for the latest release) in `migrate.py` from
```python
path = path.replace(os.sep, ".").lstrip(".")
```
to
```python
path = path.replace(os.sep, ".").lstrip(".").lstrip("/")
```

Hope it helps.

P.S. @long2ice, we still have to fix this in future updates. Maybe, we have to use `pathlib`, WDYT?

**Comment by long2ice** [comment]
This may be not path problem, could your show your project struct and config?

**Comment by TrDex** [comment]
`aerich.ini` content:
```ini
[aerich]
tortoise_orm = tools.database.TORTOISE_ORM_CONFIG
location = ./migrations
```

So, given that config, method `_get_migrate_config()` in `migrate.py` gets the `location` argument with value `./migrations` (btw, it's a default value since it's being set in [`cli.py`](https://github.com/tortoise/aerich/blob/0bbc471e0071a141c11ad972c7f098de2de63e24/aerich/cli.py#L216))

Then, **on Windows**, it works like this:
```python
>>> path = os.path.join(location, app, cls.old_models)
>>> path
'./migrations\\bot\\old_models'
```
And after replacement:
```python
>>> path = path.replace(os.sep, ".").lstrip(".")  # os.sep = '\\'
>>> path
'/migrations.bot.old_models'
```

It is possible to change `location` value in `aerich.ini` from `./migration` to `migration`, and then it works well, but I still believe that using `pathlib` is better in a long perspective.

**Comment by long2ice** [comment]
Add extra dependency to solve that problem may be a price, change default migration directory to `migration` maybe better.

**Comment by TrDex** [comment]
The `pathlib` library is included in all versions of python >= 3.4, so that's not an _extra_ dependency actually. Assuming that, I don't see much difference between doing `import os` or `import pathlib`.

Because now the default value is `./migration`, so Windows people may now be aware of this issue when they first use it.

**Comment by long2ice** [comment]
Oh, sorry, I nevey know that before, as you say, use pathlib really has better compatibility

**Comment by TrDex** [comment]
@long2ice I can work on that PR, okay?

**Comment by long2ice** [comment]
Of course, PR is welcome
